# Generated by Django 3.1.2 on 2021-01-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.URLField(max_length=150)),
                ('enlace', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idSubcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('enlace', models.URLField(max_length=150)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.URLField(max_length=150)),
                ('descripcion', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('numVotos', models.CharField(max_length=10)),
                ('enlace', models.URLField(max_length=150)),
                ('numPartidas', models.CharField(max_length=10)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
                ('idSubcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategoria')),
            ],
        ),
    ]
